version: '3.4'

services:
  parse-log:
    container_name: parse-log
    image: parse-log
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/opt/parse_log"
    user: "${UID}"
    command: parse ./logs/example.log -o test.json
